services:
  - type: web
    name: research-frontend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false
    envVars:
      - key: API_BASE_URL
        sync: false
